export const ADD_WEIGHT_DATA = "ADD_WEIGHT_DATA";
export const UPDATE_WEIGHT_DATA = "UPDATE_WEIGHT_DATA";
export const DELETE_WEIGHT_DATA = "DELETE_WEIGHT_DATA";
export const DATA_FETCH = "DATA_FETCH";
export const DATA_FETCH_SUCCESS = "DATA_FETCH_SUCCESS";
export const DATA_FETCH_FAILURE = "DATA_FETCH_FAILURE";
